
const products = [
    {
        id: 1,
        name: "GTX 1660 Ti",
        price: "200",
        category: "gpu",
        discountStatus: {
            active: false,
            amount: 0,
        },
        picture: "/DataImages/gtx1660ti.jpg",
        pictures: "",
        votes: 85,
    },
    {
        id: 2,
        name: "RTX 3060 Ti Vision",
        price: "450",
        category: "gpu",
        discountStatus: {
            active: false,
            amount: 0,
        },
        picture: "/DataImages/rtx3060tivision.jpg",
        pictures: "",
        votes: 86,
    },
    {
        id: 3,
        name: "RX 7600 Shappire Nitro",
        price: "400",
        category: "gpu",
        discountStatus: {
            active: false,
            amount: 0,
        },
        picture: "/DataImages/rx7600shappire.jpg",
        pictures: "",
        votes: 79,
    },
    {
        id: 4,
        name: "GT 1030",
        price: "74",
        category: "gpu",
        discountStatus: {
            active: false,
            amount: 0,
        },
        picture: "/DataImages/gt1030.jpg",
        pictures: "",
        votes: 55, 
    },
    {
        id: 5,
        name: "RX 7900 GRE",
        price: "569",
        category: "gpu",
        discountStatus: {
            active: false,
            amount: 0,
        },
        picture: "/DataImages/rx7900gre.png",
        pictures: "",
        votes: 82, 
    },
    {
        id: 6,
        name: "RTX 4070 Super",
        price: "599",
        category: "gpu",
        discountStatus: {
            active: false,
            amount: 0,
        },
        picture: "/DataImages/rtx4070super.png",
        pictures: "",
        votes: 77,
    },
    {
        id: 7,
        name: "i5 12400",
        price: "135",
        category: "cpu",
        discountStatus: {
            active: false,
            amount: 0,
        },
        picture: "/DataImages/i512400.jpg",
        pictures: "",
        votes: 85, 
    },
    {
        id: 8,
        name: "Ryzen 5 5600X",
        price: "140",
        category: "cpu",
        discountStatus: {
            active: false,
            amount: 0,
        },
        picture: "/DataImages/ryzen55600x.jpg",
        pictures: "",
        votes: 90, 
    },
    {
        id: 9,
        name: "Ryzen 7 5800X",
        price: "550",
        category: "cpu",
        discountStatus: {
            active: false,
            amount: 0,
        },
        picture: "/DataImages/ryzen75800x.jpg",
        pictures: "",
        votes: 84, 
    },
    {
        id: 10,
        name: "i7 14700K",
        price: "420",
        category: "cpu",
        discountStatus: {
            active: false,
            amount: 0,
        },
        picture: "/DataImages/i714700k",
        pictures: "",
        votes: 75, 
    },
    {
        id: 11,
        name: "RAM Corsair 2x8GB 3200Mhz",
        price: 60,
        category: "ram",
        discountStatus: {
            active: false,
            amount: 0,
        },
        picture: "/DataImages/vengeance2x83200.jpg",
        pictures: "",
        votes: 65, 
    },
    {
        id: 12,
        name: "Ram Corsair 2x16GB 3200Mhz",
        price: 160,
        category: "ram",
        discountStatus: {
            active: false,
            amount: 0,
        },
        picture: "/DataImages/vengeance2x163200.jpg",
        pictures: "",
        votes: 81, 
    },
    {
        id: 13,
        name: "Ram HP 16GB 3000Mhz",
        price: 40,
        category: "ram",
        discountStatus: {
            active: false,
            amount: 0,
        },
        picture: "/DataImages/hp163200.jpg",
        pictures: "",
        votes: 69, 
    },
    {
        id: 14,
        name: "Corsair 64GB 4x16 6400Mhz",
        price: 330,
        category: "ram",
        discountStatus: {
            active: false,
            amount: 0,
        },
        picture: "/DataImages/corsair646400.png",
        pictures: "",
        votes: 87, 
    },
    {
        id: 15,
        name: "Asus ROG Z790-H",
        price: 300,
        category: "mother",
        discountStatus: {
            active: false,
            amount: 0,
        },
        picture: "/DataImages/asusz790h.png",
        pictures: "",
        votes: 82, 
    },
    {
        id: 16,
        name: "Asus TUF Z790-Plus",
        price: 250,
        category: "mother",
        discountStatus: {
            active: false,
            amount: 0,
        },
        picture: "/DataImages/asus790plus.jpg",
        pictures: "",
        votes: 77, 
    },
    {
        id: 17,
        name: "ASRock Z790",
        price: 180,
        category: "mother",
        discountStatus: {
            active: false,
            amount: 0,
        },
        picture: "/DataImages/asrockz790.png",
        pictures: "",
        votes: 89, 
    },
    {
        id: 18,
        name: "MSI B760M",
        price: 200,
        category: "mother",
        discountStatus: {
            active: false,
            amount: 0,
        },
        picture: "/DataImages/msib760m.png",
        pictures: "",
        votes: 81, 
    },
    {
        id: 19,
        name: "Corsair 4000D",
        price: 104,
        category: "case",
        discountStatus: {
            active: false,
            amount: 0,
        },
        picture: "/DataImages/corsair4000d.jpg",
        pictures: "",
        votes: 95, 
    },
    {
        id: 20,
        name: "LIAN LI 011 EVO",
        price: 170,
        category: "case",
        discountStatus: {
            active: false,
            amount: 0,
        },
        picture: "/DataImages/lianli011.png",
        pictures: "",
        votes: 89, 
    },
    {
        id: 21,
        name: "Fractal North ATX mATX",
        price: 140,
        category: "case",
        discountStatus: {
            active: false,
            amount: 0,
        },
        picture: "/DataImages/fractalnorthatx.jpg",
        pictures: "",
        votes: 98, 
    },
    {
        id: 22,
        name: "Logitech G305 Wireless",
        price: 50,
        category: "mouse",
        discountStatus: {
            active: false,
            amount: 0,
        },
        picture: "/DataImages/logitechg305.jpg",
        pictures: "",
        votes: 97,
    },
    {
        id: 23,
        name: "Logitech G PRO Wireless",
        price: 82,
        category: "mouse",
        discountStatus: {
            active: false,
            amount: 0,
        },
        picture: "/DataImages/logitechgpro.jpg",
        pictures: "",
        votes: 95, 
    },
    {
        id: 24,
        name: "Razer DeathAdder V3 Wired",
        price: 70,
        category: "mouse",
        discountStatus: {
            active: false,
            amount: 0,
        },
        picture: "/DataImages/razerdeathadder.jpg",
        pictures: "",
        votes: 89, 
    },
    {
        id: 25,
        name: "BenQ Zowie ZA13-B",
        price: 35,
        category: "mouse",
        discountStatus: {
            active: false,
            amount: 0,
        },
        picture: "/DataImages/zowieza13b.jpg",
        pictures: "",
        votes: 92, 
    },
    {
        id: 26,
        name: "Redragon K582 Surara",
        price: 40,
        category: "keyboard",
        discountStatus: {
            active: false,
            amount: 0,
        },
        picture: "/DataImages/redragonk582.jpg",
        pictures: "",
        votes: 84, 
    },
    {
        id: 27,
        name: "Corsair STRAFE",
        price: 160,
        category: "keyboard",
        discountStatus: {
            active: false,
            amount: 0,
        },
        picture: "/DataImages/corsairstrafe.jpg",
        pictures: "",
        votes: 79, 
    },
    {
        id: 28,
        name: "Corsair K55",
        price: 60,
        category: "keyboard",
        discountStatus: {
            active: false,
            amount: 0,
        },
        picture: "/DataImages/corsairk55.jpg",
        pictures: "",
        votes: 87, 
    },
    {
        id: 29,
        name: "Segotep 650W 80Plus",
        price: 50,
        category: "power",
        discountStatus: {
            active: false,
            amount: 0,
        },
        picture: "/DataImages/segotep650w80plus.jpg",
        pictures: "",
        votes: 72, 
    },
    {
        id: 30,
        name: "MSI A650GL 80 Plus Gold",
        price: 90,
        category: "power",
        discountStatus: {
            active: false,
            amount: 0,
        },
        picture: "/DataImages/msia650gl.jpg",
        pictures: "",
        votes: 92, 
    },
    {
        id: 31,
        name: "Corsair RM850x 80 Plus Gold",
        price: 154,
        category: "power",
        discountStatus: {
            active: false,
            amount: 0,
        },
        picture: "/DataImages/corsair850x.png",
        pictures: "",
        votes: 90, 
    },
    {
        id: 32,
        name: "Mousepad Large 111 x 32 cm",
        price: 17,
        category: "mousepad",
        discountStatus: {
            active: false,
            amount: 0,
        },
        picture: "/DataImages/mousepad1.jpg",
        pictures: "",
        votes: 93, 
    },
    {
        id: 33,
        name: "Corsair cloth control mousepad",
        price: 30,
        category: "mousepad",
        discountStatus: {
            active: false,
            amount: 0,
        },
        picture: "/DataImages/mousepad2.jpg",
        pictures: "",
        votes: 85, 
    },
    {
        id: 34,
        name: "Corsair MM350 premium mousepad",
        price: 40,
        category: "mousepad",
        discountStatus: {
            active: false,
            amount: 0,
        },
        picture: "/DataImages/mousepad3.jpg",
        pictures: "",
        votes: 81, 
    },
    {
        id: 35,
        name: "Corsair MM350 premium mousepad",
        price: 40,
        category: "mousepad",
        discountStatus: {
            active: false,
            amount: 0,
        },
        picture: "/DataImages/mousepad3.jpg",
        pictures: "",
        votes: 81, 
    },
    {
        id: 36,
        name: "Samsung 990PRO 2TB SSD",
        price: 250,
        category: "storage",
        discountStatus: {
            active: false,
            amount: 0,
        },
        picture: "/DataImages/samsung2tb.jpg",
        pictures: "",
        votes: 89, 
    },
    {
        id: 37,
        name: "Samsung 990PRO 4TB SSD",
        price: 350,
        category: "storage",
        discountStatus: {
            active: false,
            amount: 0,
        },
        picture: "/DataImages/samsung4tb.jpg",
        pictures: "",
        votes: 91, 
    },
    {
        id: 38,
        name: "Samsung 870 EVO 4TB SSD",
        price: 345,
        category: "storage",
        discountStatus: {
            active: false,
            amount: 0,
        },
        picture: "/DataImages/samsung270evo.jpg",
        pictures: "",
        votes: 84, 
    },
    {
        id: 39,
        name: "Seagate FireCuda 4TB",
        price: 150,
        category: "storage",
        discountStatus: {
            active: false,
            amount: 0,
        },
        picture: "/DataImages/seagate4tb.jpg",
        pictures: "",
        votes: 88, 
    },
    {
        id: 40,
        name: "HyperX Cloud Stringer Core",
        price: 80,
        category: "headset",
        discountStatus: {
            active: false,
            amount: 0,
        },
        picture: "/DataImages/cloudstringer.jpg",
        pictures: "",
        votes: 92, 
    },
    {
        id: 41,
        name: "Logitech G435 LIGHTSPEED",
        price: 60,
        category: "headset",
        discountStatus: {
            active: false,
            amount: 0,
        },
        picture: "/DataImages/logitechg435.jpg",
        pictures: "",
        votes: 79, 
    },
    {
        id: 42,
        name: "Corsair HS270 PRO",
        price: 110,
        category: "headset",
        discountStatus: {
            active: false,
            amount: 0,
        },
        picture: "/DataImages/corsairhs70.jpg",
        pictures: "",
        votes: 75, 
    },
    {
        id: 43,
        name: "HyperX Cloud II",
        price: 80,
        category: "headset",
        discountStatus: {
            active: false,
            amount: 0,
        },
        picture: "/DataImages/hyperxcloudii.jpg",
        pictures: "",
        votes: 99,
    },
    {
        id: 44,
        name: "Dowinx Gaming Chair",
        price: 190,
        category: "chair",
        discountStatus: {
            active: false,
            amount: 0,
        },
        picture: "/DataImages/dowinxchair.jpg",
        pictures: "",
        votes: 82,
    },
    {
        id: 45,
        name: "Raidmax Cloth Chair",
        price: 150,
        category: "chair",
        discountStatus: {
            active: false,
            amount: 0,
        },
        picture: "/DataImages/raidmaxchair.jpg",
        pictures: "",
        votes: 97,
    },
    {
        id: 46,
        name: "Acer Aspire 5",
        price: 700,
        category: "notebook",
        discountStatus: {
            active: false,
            amount: 0,
        },
        picture: "/DataImages/aceraspire5.jpg",
        pictures: "",
        votes: 92,
    },
    {
        id: 47,
        name: "MSI Creator Z16",
        price: 2000,
        category: "notebook",
        discountStatus: {
            active: false,
            amount: 0,
        },
        picture: "/DataImages/msicreatorz16.jpg",
        pictures: "",
        votes: 85,
    },
    {
        id: 48,
        name: "Asus TUF Gaming 2K",
        price: 200,
        category: "screen",
        discountStatus: {
            active: false,
            amount: 0,
        },
        picture: "/DataImages/asustufgaming.png",
        pictures: "",
        votes: 89,
    },
    {
        id: 49,
        name: "Crua 1080p 170hz",
        price: 180,
        category: "screen",
        discountStatus: {
            active: false,
            amount: 0,
        },
        picture: "/DataImages/crua1080.jpg",
        pictures: "",
        votes: 100,
    },
    {
        id: 50,
        name: "Asus ROG Swift 4k OLED",
        price: 1300,
        category: "screen",
        discountStatus: {
            active: false,
            amount: 0,
        },
        picture: "/DataImages/asusrog.jpg",
        pictures: "",
        votes: 97,
    },
    
]

export default products;